### ISSUE TITLE
Add texture filter settings

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/texture#32]
See https://github.com/PistonDevelopers/opengl_graphics/issues/207.

This can be added to `TextureSettings`.

- [x] Add `min: Filter` to `TextureSettings` (default should be `Filter::Linear`)
- [x] Add `mag: Filter` to `TextureSettings` (default should be `Filter::Linear`)
- [x] Add `mipmap: Filter` in `TextureSettings` (default should be `Filter::Linear`)
- [x] Add enum `Filter { Nearest, Linear }`
- [x] Add `TextureSettings::get_min`
- [x] Add `TextureSettings::get_mag`
- [x] Add `TextureSettings::get_mipmap`
- [x] Add `TextureSettings::set_min`
- [x] Add `TextureSettings::set_mag`
- [x] Add `TextureSettings::set_mipmap`
- [x] Add `TextureSettings::set_filter` (sets both min and mag filter)
- [x] Add `TextureSettings::min` (builder method)
- [x] Add `TextureSettings::mag` (builder method)
- [x] Add `TextureSettings::mipmap` (builder method)
- [x] Add `TextureSettings::filter` (builder method, sets both min and mag filter)

**Comment by bvssvni** [comment]
An alternative is to remove `generate_mipmap` to avoid confusion. If `mipmap_filter` is set, then mipmaps will be generated.

**Comment by bvssvni** [comment]
Another alternative is to keep `generate_mipmap`. It must be set to `true` to generate mipmaps, or else `mipmap_filter` is ignored. If `mipmap_filter` is `None` then it could use same settings as `min_filter`.

**Comment by bvssvni** [comment]
Another alternative is to keep `generate_mipmap`, but use `mipmap_filter: Filter` (with default set to `Linear`).

**Comment by bvssvni** [comment]
We could also skip the `_filter` suffix since we type `mag(Filter::Linear)`.

**Comment by SDBlumire** [comment]
Myself and @bvssvni had a discussion with regards to how the mipmap settings should be handled.

In OpenGL, there are 6 filters, summarised as follows

| Param Setting | Linear within mip-level | Has mipmapping | Linear between mip-levels |
|---------------------------|-------------------------|----------------|---------------------------|
| GL_NEAREST | No | No |  |
| GL_LINEAR | Yes | No |  |
| GL_NEAREST_MIPMAP_NEAREST | No | Yes | No |
| GL_LINEAR_MIPMAP_NEAREST | Yes | Yes | No |
| GL_NEAREST_MIPMAP_LINEAR | No | Yes | Yes |
| GL_LINEAR_MIPMAP_LINEAR | Yes | Yes | Yes |

There are two approaches that could be taken to encode this, the first would be to use

    filter: Filter,
    mipmap_filter: Option<Filter>

which would directly mimic the behaviour visible in the OpenGL filters. However, this clashes with the current API, which tracks a `generate_mipmap` boolean value. As such, so as to maintain compatability with this.

    filter: Filter,
    mipmap_filter: Filter,
    generate_mipmap: bool

This would maintain compatability with the current system, at the cost of being further removed conceptually from the OpenGL implementation.

The above todo list is based on the maintaining compatability side of things.

**Comment by SDBlumire** [comment]
Additionally, some updates would need to be made to other libraries so as to benefit from this change. Gfx currently hard-codes to generating mipmaps using Nearest neighbour, and opengl_graphics currently hard-codes to using Linear, both of thse would need to be updated to no longer hard code and to instead use the new settings described above. There may be other places that should be updated to benefit from these changes, but these are the two which most obviously spring to mind.

**Comment by bvssvni** [comment]
Use cases:

- `TextureSettings::new().generate_mipmap(true)` - turn on mip map, use `Filter::Linear` by default, no need to call `mipmap`.
- `TextureSettings::new().filter(Filter::Nearest).mipmap(Filter::Nearest)` - turn on mip map, no need to call `generate_mipmap`.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/texture/pull/33
