### ISSUE TITLE
Options for texture wrapping

### ISSUE THREAD

**Issue by sphereflow** [PistonDevelopers/texture#49]
Hi, I have added support for texture wrapping and added examples in the gfx_graphics and opengl_graphics repositories.
1. Can I submit a pull request?
2. Should I name texture coordinates u v or s t like OpenGL does?
3. I have made changes to the following repositories:
  - [https://github.com/PistonDevelopers/texture](https://github.com/PistonDevelopers/texture)
  - [https://github.com/PistonDevelopers/gfx_graphics](https://github.com/PistonDevelopers/gfx_graphics)
  - [https://github.com/PistonDevelopers/gfx_texture](https://github.com/PistonDevelopers/gfx_texture)
  - [https://github.com/PistonDevelopers/opengl_graphics](https://github.com/PistonDevelopers/opengl_graphics)
I am unsure which versions to bump, if any.
Edit:
Relevant pull requests:
#50 
[https://github.com/PistonDevelopers/opengl_graphics/pull/314](https://github.com/PistonDevelopers/opengl_graphics/pull/314)
[https://github.com/PistonDevelopers/gfx_texture/pull/119](https://github.com/PistonDevelopers/gfx_texture/pull/119)
[https://github.com/PistonDevelopers/gfx_graphics/pull/361](https://github.com/PistonDevelopers/gfx_graphics/pull/361)

**Comment by bvssvni** [comment]
1. Yes!
2. I prefer u v.
3. Just make PRs, then I'll merge them and do the bumps (I use a tool called "Eco" for analyzing dependencies).

**Comment by bvssvni** [comment]
Thanks for the PRs!
